### ISSUE TITLE
Gross-/Kleinschreibung Komponententitel

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#201]
Siehe Screenshot werden in Komponententiteln alle Wörter gross begonnen, auch wenn z.B. das Folgewort "Interesse anmelden" kleingeschrieben ist.

**Comment by innosmith** [comment]
Danke. Habe das CSS auf PROD kopiert.

**Comment by larsUE** [comment]
@innosmith : Kannst du mir die CSS-Anpassung schicken oder hier posten? Das wäre auch auf der Mitwirken-Plattform nützlich.

**Comment by carlobeltrame** [comment]
```css
.process-nav__link {
  text-transform: uppercase;
}
```
