### ISSUE TITLE
Notification-Funktion funktioniert nicht

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#241]
Siehe Screenshots kann ein angemeldeter User zumindest auf MeinQuartier.Zuerich die Notifications (oranges Glöckchen) nicht anzeigen.

![Screenshot 2022-05-04 at 10 16 58](https://user-images.githubusercontent.com/75796635/166645517-acf83ac2-3551-4e5e-8aa7-4b5bf68f40c4.png)
![Screenshot 2022-05-04 at 10 17 45](https://user-images.githubusercontent.com/75796635/166645531-b9f51425-c798-4653-bf15-09f76c9d4a8d.png)

**Comment by larsUE** [comment]
@innosmith Der Fehler [ist bekannt](https://github.com/puzzle/decidim-zuerich/issues/149#issuecomment-1088727748) und tritt auch auf der Mitwirkenplattform auf. Es betrifft wohl eine Notifizierungsklasse, die nicht richtig angezeigt wird.

**Comment by innosmith** [comment]
@larsUE : hätte ich genauer gelesen ;-) soll ich das Ticket auf Done stellen?

**Comment by larsUE** [comment]
@innosmith Nein, lass mal so. Wir haben für die restlichen offenen Punkte so oder so einzelne Tickets geschaffen, da die Liste etwas unübersichtlich wurde.

**Comment by carlobeltrame** [comment]
Ich konnte ein Problem fixen. Das hatte mal noch nichts mit Kommentaren zu tun. Wenn ein Vorschlag erstellt wird, dann versucht Decidim seit [Dezember](https://github.com/decidim/decidim/pull/8603), den*die Autor*in anzuzeigen. Da drin steckt aber ein Bug: Wenn ein Proposal im Admin-Backend erstellt wird, und der Autor somit Mitwirken Zürich oder MeinQuartier.zuerich ist (der Tenant, nicht ein wirklicher User), dann fällt dieses neue Feature auf die Nase.

Die ersten paar Seiten mit Benachrichtigungen funktionieren in meinem Account jetzt. Es gibt aber auf einer Seite weiter hinten nochmals ein Crash. Dem gehe ich aktuell noch nach.

**Comment by carlobeltrame** [comment]
Lars blendet für den Moment mal via CSS die zwei Links zu den Notifications aus.

**Comment by carlobeltrame** [comment]
Hier die Übersetzungen die ich in Luzern ergänzt hatte um den aktuellen Fehler zu fixen. Z.B. `de.time.formats.day_of_month` auf `%d. %b` übersetzen und so weiter.
```yaml
de:
  time:
    formats:
      day_of_month: "%d. %b"
      day_of_week: "%a"
      day_of_week_long: "%a %e"
      day_of_year: "%d.%m.%y"
      ddmm: "%d.%m."
      ddmmyyyy: "%d.%m.%Y"
      decidim_day_of_year: "%d %B %Y"
      decidim_short: "%d.%m.%Y %H:%M"
      default: "%a, %d.%b.%Y %H:%M:%S %z"
      devise:
        mailer:
          invitation_instructions:
            accept_until_format: "%d.%B.%Y %I:%M %p"
      long: "%d.%B.%Y %H:%M"
      long_dashed: "%Y-%m-%d %H:%M:%S"
      short: "%d.%m.%Y %H:%M"
      time_of_day: "%H:%M"
```
